# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfb2d93e11de927eebc1c58ee9ab7d6fa37cb33c62a90df7ddb680737c093548bba6af76130a3a35895610bd6360ded8fa0b8a44cf8dba38019b65d55ca629ee

test:
  secret_key_base: fb99fc8b594c87125e66a3bff444951b778f280461dd15f031caaba9da8ff0570deb03b4bf8f9d93e844081e57770861e10687ce4923233f0dc44e42cc62afa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
